apiVersion: v1
kind: Secret
metadata:
  name: taskapi-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: "taskuser"
  POSTGRES_PASSWORD: "changeme_secure"
  POSTGRES_DB: "taskdb"
  REDIS_PASSWORD: "redis_secret"
